package apps;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author HiTech
 */
public class doctor3 extends javax.swing.JFrame {

    Connection con;

    /**
     * Creates new form doctor3
     */
    public doctor3() {
        initComponents();
        setLocationRelativeTo(null);
        try {

            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital", "root", "root");
        } catch (SQLException ex) {
            Logger.getLogger(DoctorForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btn_phon = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_syp = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btn_med = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btn_not = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btn_gen = new javax.swing.JTextField();
        btn_male = new javax.swing.JRadioButton();
        btn_female = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btn_age = new javax.swing.JComboBox<>();
        btn_blood = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        btn_id = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Patient Info");

        jPanel2.setBackground(new java.awt.Color(0, 153, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Patient Data");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("ID");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 30, -1));
        jPanel2.add(btn_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 120, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("phone");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(496, 99, -1, -1));

        btn_phon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_phonActionPerformed(evt);
            }
        });
        jPanel2.add(btn_phon, new org.netbeans.lib.awtextra.AbsoluteConstraints(642, 95, 137, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("age");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 169, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("syptoms");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(496, 169, -1, -1));
        jPanel2.add(btn_syp, new org.netbeans.lib.awtextra.AbsoluteConstraints(642, 165, 137, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("medicine");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 231, -1, -1));

        btn_med.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_medActionPerformed(evt);
            }
        });
        jPanel2.add(btn_med, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 227, 111, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("blood type");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(496, 231, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("notice");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 308, -1, -1));
        jPanel2.add(btn_not, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 304, 111, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("genetic diseases");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(496, 308, -1, -1));

        btn_gen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_genActionPerformed(evt);
            }
        });
        jPanel2.add(btn_gen, new org.netbeans.lib.awtextra.AbsoluteConstraints(652, 304, 127, 30));

        buttonGroup1.add(btn_male);
        btn_male.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_male.setText("male");
        jPanel2.add(btn_male, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 373, -1, -1));

        buttonGroup1.add(btn_female);
        btn_female.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_female.setText("female");
        jPanel2.add(btn_female, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 373, -1, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 470, -1, -1));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setText("back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 470, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("gender");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 375, -1, -1));

        btn_age.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97", "98", "99", "100", " " }));
        btn_age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ageActionPerformed(evt);
            }
        });
        jPanel2.add(btn_age, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, -1));

        btn_blood.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A-", "A+", "B+", "B-", "O+", "O-", "AB+", "AB-", " " }));
        jPanel2.add(btn_blood, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 232, -1, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("name");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        btn_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btn_idKeyReleased(evt);
            }
        });
        jPanel2.add(btn_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 120, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wallpapersy.jpg"))); // NOI18N
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here
        if (btn_name.getText().equals("") || btn_med.getText().equals("") || btn_not.getText().equals("") || btn_phon.getText().isEmpty() || btn_gen.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "please ");
        } else {
            try {

                int id = Integer.parseInt(btn_id.getText());
                String medicine = btn_med.getText();
                String note = btn_not.getText();
                String syp = btn_syp.getText();
                String gen = btn_gen.getText();
                PreparedStatement stmt = con.prepareStatement("update patient set p_med=?,p_note=?,p_syp=?,p_gen=? where p_id=?");
                stmt.setString(1, medicine);
                stmt.setString(2, note);
                stmt.setString(3, syp);
                stmt.setString(4, gen);
                stmt.setInt(5, id);
                stmt.executeUpdate();
                JOptionPane.showMessageDialog(null, "save success");
                btn_age.setSelectedIndex(0);
                btn_blood.setSelectedIndex(0);
                btn_gen.setText("");
                btn_id.setText("");
                btn_med.setText("");
                btn_name.setText("");
                btn_not.setText("");
                btn_phon.setText("");
                btn_syp.setText("");
            } catch (SQLException ex) {
                Logger.getLogger(doctor3.class.getName()).log(Level.SEVERE, null, ex);
            }

    }//GEN-LAST:event_jButton1ActionPerformed
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        doctor2 doc = new doctor2();
        doc.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btn_medActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_medActionPerformed

    }//GEN-LAST:event_btn_medActionPerformed

    private void btn_phonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_phonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_phonActionPerformed

    private void btn_genActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_genActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_genActionPerformed

    private void btn_ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ageActionPerformed

    private void btn_idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_idKeyReleased
        String id = btn_id.getText();

        try {
            PreparedStatement stmt = con.prepareStatement("select * from patient where p_id=?");

            stmt.setString(1, id);
            ResultSet rs = stmt.executeQuery();
            while (rs.next()) {
                if (id.equals(rs.getString("p_id"))) {
                    btn_name.setText(rs.getString("p_f_name"));
                    btn_phon.setText(rs.getString("p_phoneNum"));
                    btn_age.setSelectedItem(rs.getString("p_age"));
                    btn_blood.setSelectedItem(rs.getString("p_bloodType"));
                    String st = rs.getString("p_gender");
                    if (st.equals("male")) {
                        btn_male.setSelected(true);
                    } else {
                        btn_female.setSelected(true);
                    }

                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(NurseForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_idKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(doctor3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(doctor3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(doctor3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(doctor3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new doctor3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> btn_age;
    private javax.swing.JComboBox<String> btn_blood;
    private javax.swing.JRadioButton btn_female;
    private javax.swing.JTextField btn_gen;
    private javax.swing.JTextField btn_id;
    private javax.swing.JRadioButton btn_male;
    private javax.swing.JTextField btn_med;
    private javax.swing.JTextField btn_name;
    private javax.swing.JTextField btn_not;
    private javax.swing.JTextField btn_phon;
    private javax.swing.JTextField btn_syp;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    private Object getText() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
