/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package apps;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Mohammed Hussain
 */
public class DoctorForm extends javax.swing.JFrame {

    Connection con;

    /**
     * Creates new form DoctorForm
     */
    public DoctorForm() {
        initComponents();

        setLocationRelativeTo(null);
        try {

            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital", "root", "root");
        } catch (SQLException ex) {
            Logger.getLogger(DoctorForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        fillcompobox();
    }

    public void fillcompobox() {
        try {
            PreparedStatement stmt = con.prepareStatement("select d_dept from doctor");
            ResultSet rs = stmt.executeQuery();
            while (rs.next()) {
                btn_dept.addItem(rs.getString(1));

            }
        } catch (SQLException ex) {
            Logger.getLogger(DoctorForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btn_address = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btn_dept = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        btn_user = new javax.swing.JTextField();
        btn_spe = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btn_phone = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btn_pass = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        btn_male = new javax.swing.JRadioButton();
        btn_female = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        btn_age = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btn_leave = new javax.swing.JComboBox<>();
        btn_join = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btn_id = new javax.swing.JTextField();
        btn_update = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Doctor Form");

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Address :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 139, 39));

        btn_address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addressActionPerformed(evt);
            }
        });
        jPanel1.add(btn_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 320, 240, 32));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Specialization :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 139, 72));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Department :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 139, 37));

        jPanel1.add(btn_dept, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, 149, 48));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setText("Welcom To Register Form");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 323, 44));
        jPanel1.add(btn_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 116, 230, 30));
        jPanel1.add(btn_spe, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 390, 240, 32));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Untitled.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 6, 100, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("User Name :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 117, 127, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Doctor Name :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 165, 127, 32));

        btn_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nameActionPerformed(evt);
            }
        });
        jPanel1.add(btn_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 230, 33));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Phone Number :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 238, -1, 42));

        btn_phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_phoneActionPerformed(evt);
            }
        });
        jPanel1.add(btn_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 246, 230, 32));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Password :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 98, 97, -1));
        jPanel1.add(btn_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 100, 110, 29));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Gender :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 150, 94, 53));

        buttonGroup1.add(btn_male);
        btn_male.setText("Male");
        jPanel1.add(btn_male, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 211, 98, -1));

        buttonGroup1.add(btn_female);
        btn_female.setText("Female");
        btn_female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_femaleActionPerformed(evt);
            }
        });
        jPanel1.add(btn_female, new org.netbeans.lib.awtextra.AbsoluteConstraints(675, 211, 98, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("age:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, 79, 30));

        btn_age.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97", "98", "99", "100" }));
        jPanel1.add(btn_age, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 270, 90, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("shift ");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 350, 85, 24));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setText("Join :");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 400, 70, 30));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setText("Leave :");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 450, 70, 30));

        btn_leave.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "12:00 AM", "1:00 AM", "2:00 AM", "3:00 AM", "4:00 AM", "5:00 AM", "6:00 AM", "7:00 AM", "8:00 AM", "9:00 AM", "10:00 AM", "11:00 AM", "12:00 PM", "1:00 PM", "2:00 PM", "3:00 PM", "4:00 PM", "5:00 PM", "6:00 PM", "7:00 PM", "8:00 PM", "9:00 PM", "10:00 PM", "11:00 PM" }));
        jPanel1.add(btn_leave, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 450, 180, 30));

        btn_join.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "12:00 AM", "1:00 AM", "2:00 AM", "3:00 AM", "4:00 AM", "5:00 AM", "6:00 AM", "7:00 AM", "8:00 AM", "9:00 AM", "10:00 AM", "11:00 AM", "12:00 PM", "1:00 PM", "2:00 PM", "3:00 PM", "4:00 PM", "5:00 PM", "6:00 PM", "7:00 PM", "8:00 PM", "9:00 PM", "10:00 PM", "11:00 PM" }));
        btn_join.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_joinActionPerformed(evt);
            }
        });
        jPanel1.add(btn_join, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 400, 180, 30));

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 510, -1, -1));

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        jPanel1.add(saveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 510, -1, -1));
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 40, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setText("ID :");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 60, 70, 30));

        btn_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_idActionPerformed(evt);
            }
        });
        btn_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btn_idKeyReleased(evt);
            }
        });
        jPanel1.add(btn_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 60, 110, 30));

        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        jPanel1.add(btn_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 510, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wallpapersy.jpg"))); // NOI18N
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_femaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_femaleActionPerformed

    private void btn_addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_addressActionPerformed

    private void btn_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_nameActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        if (btn_user.getText().equals("") || btn_name.getText().equals("") || btn_address.getText().equals("") || btn_spe.getText().isEmpty() || btn_phone.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Make sure you enter all fields ");
        } else {
            try {

                String username = btn_user.getText();
                String password = btn_pass.getText();
                String doctorname = btn_name.getText();
                String specialzatoin = btn_spe.getText();
                String address = btn_address.getText();
                int phone = Integer.parseInt(btn_phone.getText());
                String department = (String) btn_dept.getSelectedItem();
                int year = Integer.parseInt((String) btn_age.getSelectedItem());
                String join = (String) btn_join.getSelectedItem();
                String end = (String) btn_leave.getSelectedItem();
                String gender;
                if (btn_male.isSelected()) {
                    gender = "male";
                } else {
                    gender = "female";
                }
                PreparedStatement stmt = con.prepareStatement("insert into doctor (d_username,d_password,d_name,d_phoneNum,d_address,d_sep,d_dept,d_gender,d_age,d_join,d_leave) values (?,?,?,?,?,?,?,?,?,?,?)");

                stmt.setString(1, username);
                stmt.setString(2, password);
                stmt.setString(3, doctorname);
                stmt.setInt(4, phone);
                stmt.setString(5, address);
                stmt.setString(6, specialzatoin);
                stmt.setString(7, department);
                stmt.setString(8, gender);
                stmt.setInt(9, year);
                stmt.setString(10, join);
                stmt.setString(11, end);
                stmt.executeUpdate();
                JOptionPane.showMessageDialog(null, ("save data success"));
                btn_user.setText("");
                btn_pass.setText("");
                btn_name.setText("");
                btn_phone.setText("");
                btn_address.setText("");
                btn_spe.setText("");
                buttonGroup1.clearSelection();
                btn_dept.setSelectedIndex(0);
                btn_age.setSelectedIndex(0);
                btn_join.setSelectedIndex(0);
                btn_leave.setSelectedIndex(0);
                btn_id.setText("");
            } catch (SQLException ex) {
                Logger.getLogger(DoctorForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_saveButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        afterLogin af = new afterLogin();
        af.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_phoneActionPerformed

    private void btn_joinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_joinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_joinActionPerformed

    private void btn_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_idActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        if (btn_user.getText().equals("") || btn_name.getText().equals("") || btn_address.getText().equals("") || btn_spe.getText().isEmpty() || btn_phone.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Make sure you enter all fields ");
        } else {
            try {
                int id = Integer.parseInt(btn_id.getText());
                String username = btn_user.getText();
                String password = btn_pass.getText();
                String doctorname = btn_name.getText();
                String specialzatoin = btn_spe.getText();
                String address = btn_address.getText();
                int phone = Integer.parseInt(btn_phone.getText());
                String department = (String) btn_dept.getSelectedItem();
                int year = Integer.parseInt((String) btn_age.getSelectedItem());
                String join = (String) btn_join.getSelectedItem();
                String end = (String) btn_leave.getSelectedItem();
                String gender;
                if (btn_male.isSelected()) {
                    gender = "male";
                } else {
                    gender = "female";
                }
                PreparedStatement stmt = con.prepareStatement("update doctor set d_username=?,d_password=?,d_name=?,d_phoneNum=?,d_address=?,d_sep=?,d_dept=?,d_gender=?,d_age=?,d_join=?,d_leave=? where doctor_id=?");

                stmt.setString(1, username);
                stmt.setString(2, password);
                stmt.setString(3, doctorname);
                stmt.setInt(4, phone);
                stmt.setString(5, address);
                stmt.setString(6, specialzatoin);
                stmt.setString(7, department);
                stmt.setString(8, gender);
                stmt.setInt(9, year);
                stmt.setString(10, join);
                stmt.setString(11, end);
                stmt.setInt(12, id);
                stmt.executeUpdate();
                JOptionPane.showMessageDialog(null, ("update data success"));
                btn_user.setText("");
                btn_pass.setText("");
                btn_name.setText("");
                btn_phone.setText("");
                btn_address.setText("");
                btn_spe.setText("");
                buttonGroup1.clearSelection();
                btn_dept.setSelectedIndex(0);
                btn_age.setSelectedIndex(0);
                btn_join.setSelectedIndex(0);
                btn_leave.setSelectedIndex(0);
                btn_id.setText("");
            } catch (SQLException ex) {
                Logger.getLogger(DoctorForm.class.getName()).log(Level.SEVERE, null, ex);
            }

    }//GEN-LAST:event_btn_updateActionPerformed
    }
    private void btn_idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_idKeyReleased
        try {
            String id = btn_id.getText();
            PreparedStatement stmt = con.prepareStatement("select * from doctor where doctor_id=?");
            stmt.setString(1, id);
            ResultSet rs = stmt.executeQuery();
            while (rs.next()) {
                if (id.equals(rs.getString("doctor_id"))) {
                    btn_address.setText(rs.getString("d_address"));
                    btn_age.setSelectedItem(rs.getString("d_age"));
                    btn_dept.setSelectedItem(rs.getString("d_dept"));
                    btn_join.setSelectedItem(rs.getString("d_join"));
                    btn_leave.setSelectedItem(rs.getString("d_leave"));
                    btn_name.setText(rs.getString("d_name"));
                    btn_pass.setText(rs.getString("d_password"));
                    btn_phone.setText(rs.getString("d_phoneNum"));
                    btn_user.setText(rs.getString("d_username"));
                    btn_spe.setText(rs.getString("d_sep"));
                    String st = rs.getString("d_gender");
                    if (st.equals("male")) {
                        btn_male.setSelected(true);
                    } else {
                        btn_female.setSelected(true);
                    }
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(DoctorForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_idKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoctorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoctorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoctorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoctorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoctorForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField btn_address;
    private javax.swing.JComboBox<String> btn_age;
    private javax.swing.JComboBox<String> btn_dept;
    private javax.swing.JRadioButton btn_female;
    private javax.swing.JTextField btn_id;
    private javax.swing.JComboBox<String> btn_join;
    private javax.swing.JComboBox<String> btn_leave;
    private javax.swing.JRadioButton btn_male;
    private javax.swing.JTextField btn_name;
    private javax.swing.JPasswordField btn_pass;
    private javax.swing.JTextField btn_phone;
    private javax.swing.JTextField btn_spe;
    private javax.swing.JButton btn_update;
    private javax.swing.JTextField btn_user;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
