/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package apps;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Harou
 */
public
        class newpa extends javax.swing.JFrame {
Connection con;
    /**
     * Creates new form newpa
     */
    public
            newpa() {
        initComponents();
                setLocationRelativeTo(null);
    try {
        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital","root", "root");
    } catch (SQLException ex) {
        Logger.getLogger(newpa.class.getName()).log(Level.SEVERE, null, ex);
    }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btn_phone = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btn_add = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btn_city = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btn_d1 = new javax.swing.JComboBox<>();
        btn_d2 = new javax.swing.JComboBox<>();
        btn_d3 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btn_bloodtype = new javax.swing.JComboBox<>();
        btn_name = new javax.swing.JTextField();
        btn_save = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btn_name2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        btn_name3 = new javax.swing.JTextField();
        btn_male = new javax.swing.JRadioButton();
        btn_female = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_single = new javax.swing.JRadioButton();
        btn_married = new javax.swing.JRadioButton();
        btn_age = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        btn_Ubdate = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        btn_id = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "NewPatient", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 1, 14))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(btn_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 213, 223, 41));

        jLabel7.setText("Address");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 266, 73, 38));
        jPanel1.add(btn_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 266, 223, 38));

        jLabel8.setText("city");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 322, 57, 36));
        jPanel1.add(btn_city, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 322, 223, 36));

        jLabel5.setText("Age");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 128, 71, 32));

        jLabel9.setText("gender");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 166, 77, 35));

        jLabel10.setText("date of come");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 380, 73, -1));

        btn_d1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPanel1.add(btn_d1, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 370, -1, 36));

        btn_d2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", " " }));
        jPanel1.add(btn_d2, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 370, -1, 36));

        btn_d3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2022" }));
        jPanel1.add(btn_d3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, -1, 36));

        jLabel11.setText("blood type");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 418, 73, 42));

        jLabel1.setText("first name");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 23, 60, 27));

        btn_bloodtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A-", "A+", "B+", "B-", "O+", "O-", "AB+", "AB-" }));
        jPanel1.add(btn_bloodtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 418, 59, 42));
        jPanel1.add(btn_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 23, 232, 27));

        btn_save.setText("save ");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });
        jPanel1.add(btn_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 500, -1, -1));

        jLabel2.setText("middle name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 56, 71, 27));
        jPanel1.add(btn_name2, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 56, 232, 27));

        jLabel3.setText("last name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 89, 71, 27));

        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 500, -1, -1));
        jPanel1.add(btn_name3, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 89, 232, 27));

        buttonGroup1.add(btn_male);
        btn_male.setText("male");
        btn_male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_maleActionPerformed(evt);
            }
        });
        jPanel1.add(btn_male, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 98, 35));

        buttonGroup1.add(btn_female);
        btn_female.setText("female");
        jPanel1.add(btn_female, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 166, 98, 35));

        jLabel6.setText("phone num");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 213, 73, 41));

        jLabel4.setText("Martial Status");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 478, -1, 35));

        buttonGroup2.add(btn_single);
        btn_single.setText("Single");
        btn_single.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_singleActionPerformed(evt);
            }
        });
        jPanel1.add(btn_single, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 478, 91, 35));

        buttonGroup2.add(btn_married);
        btn_married.setText("Married");
        btn_married.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_marriedActionPerformed(evt);
            }
        });
        jPanel1.add(btn_married, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 478, 91, 35));

        btn_age.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97", "98", "99", "100" }));
        btn_age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ageActionPerformed(evt);
            }
        });
        jPanel1.add(btn_age, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 128, 98, 32));

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel12.setText("NewPatient");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 120, 30));

        btn_Ubdate.setText("update");
        btn_Ubdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UbdateActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Ubdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 500, -1, -1));

        jLabel14.setText("id");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, -1, -1));

        btn_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_idActionPerformed(evt);
            }
        });
        btn_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btn_idKeyReleased(evt);
            }
        });
        jPanel1.add(btn_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, 100, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wallpapersy.jpg"))); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        // TODO add your handling code here:

        if(!btn_name.getText().isEmpty()&& !btn_name2.getText().isEmpty()&&!btn_name3.getText().isEmpty())
        {
            try {
                String firstname=btn_name.getText();
                String middlename=btn_add.getText();
                String lastname=btn_add.getText();
                String gender;
                if(btn_male.isSelected())
                    gender="male";
                else
                    gender="female";
                String stat;
                if(btn_single.isSelected())
                    stat="Single";
                else
                    stat="Married";
                int age=Integer.parseInt((String)btn_age.getSelectedItem());
                int ph=Integer.parseInt(btn_phone.getText());
                String cit=btn_city.getText();
                String add=btn_add.getText();
                String date1=btn_d1.getSelectedItem().toString();
                String date2=btn_d2.getSelectedItem().toString();
                String date3=btn_d3.getSelectedItem().toString();
                String bloodtypes=btn_bloodtype.getSelectedItem().toString();
                PreparedStatement stmt=con.prepareStatement("insert into patient (p_f_name ,p_m_name ,p_l_name ,p_age ,p_gender,p_phoneNum ,p_address,p_city ,p_dateDay ,p_dateMonth ,p_dateYear ,p_bloodType ,p_MartialStatus) values (?,?,?,?,?,?,?,?,?,?,?,?,?) ");
                stmt.setString(1, firstname);
                stmt.setString(2, middlename);
                stmt.setString(3, lastname);
                stmt.setInt(4, age);
                stmt.setString(5, gender);
                stmt.setInt(6, ph);
               
                stmt.setString(7, add);
                stmt.setString(8, cit);
                stmt.setString(9, date1);
                stmt.setString(10, date2);
                stmt.setString(11, date3);
                stmt.setString(12, bloodtypes);
                stmt.setString(13, stat);
                stmt.executeUpdate();
                JOptionPane.showMessageDialog(this, "save data success");
                btn_add.setText(" ");
                btn_name.setText("");
                btn_name2.setText("");
                btn_name3.setText("");
                btn_city.setText("");
                btn_phone.setText("");
                btn_bloodtype.setSelectedIndex(0);
                btn_d1.setSelectedIndex(0);
                btn_d2.setSelectedIndex(0);
                btn_d3.setSelectedIndex(0);
                btn_age.setSelectedIndex(0);
                buttonGroup1.clearSelection();
                buttonGroup2.clearSelection();
            } catch (SQLException ex) {
                Logger.getLogger(newpa.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btn_saveActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        resppage another=new resppage();
        another.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btn_singleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_singleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_singleActionPerformed

    private void btn_marriedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_marriedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_marriedActionPerformed

    private void btn_maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_maleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_maleActionPerformed

    private void btn_ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ageActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btn_ageActionPerformed

    private void btn_UbdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UbdateActionPerformed
        try {
            int id=Integer.parseInt(btn_id.getText());
                String firstname=btn_name.getText();
                String middlename=btn_add.getText();
                String lastname=btn_add.getText();
                String gender;
                if(btn_male.isSelected())
                    gender="male";
                else
                    gender="female";
                String stat;
                if(btn_single.isSelected())
                    stat="Single";
                else
                    stat="Married";
                int age=Integer.parseInt((String)btn_age.getSelectedItem());
                int ph=Integer.parseInt(btn_phone.getText());
                String cit=btn_city.getText();
                String add=btn_add.getText();
                String date1=btn_d1.getSelectedItem().toString();
                String date2=btn_d2.getSelectedItem().toString();
                String date3=btn_d3.getSelectedItem().toString();
                String bloodtypes=btn_bloodtype.getSelectedItem().toString();
                PreparedStatement stmt=con.prepareStatement("update patient set p_f_name=? ,p_m_name=? ,p_l_name=? ,p_age=? ,p_gender=?,p_phoneNum=? ,p_address=?,p_city=? ,p_dateDay =?,p_dateMonth=?,p_dateYear =?,p_bloodType =?,p_MartialStatus=? where p_id=? ");
                stmt.setString(1, firstname);
                stmt.setString(2, middlename);
                stmt.setString(3, lastname);
                stmt.setInt(4, age);
                stmt.setString(5, gender);
                stmt.setInt(6, ph);
                stmt.setString(7, add);
                stmt.setString(8, cit);
                stmt.setString(9, date1);
                stmt.setString(10, date2);
                stmt.setString(11, date3);
                stmt.setString(12, bloodtypes);
                stmt.setString(13, stat);
                stmt.setInt(14, id);
                stmt.executeUpdate();
                JOptionPane.showMessageDialog(this, "update data success");
                btn_add.setText(" ");
                btn_name.setText("");
                btn_name2.setText("");
                btn_name3.setText("");
                btn_city.setText("");
                btn_phone.setText("");
                btn_id.setText("");
                btn_bloodtype.setSelectedIndex(0);
                btn_d1.setSelectedIndex(0);
                btn_d2.setSelectedIndex(0);
                btn_d3.setSelectedIndex(0);
                btn_age.setSelectedIndex(0);
                buttonGroup1.clearSelection();
                buttonGroup2.clearSelection();
            } catch (SQLException ex) {
                Logger.getLogger(newpa.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_btn_UbdateActionPerformed

    private void btn_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_idActionPerformed

    private void btn_idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_idKeyReleased
       String id=btn_id.getText();
       try {
            PreparedStatement stmt=con.prepareStatement("select * from patient where p_id=?");
            stmt.setString(1, id);
            ResultSet rs=stmt.executeQuery();
           
            if(rs.next())
        {
            if(id.equals(rs.getString("p_id")))
            {
                btn_add.setText(rs.getString("p_address"));
                btn_city.setText(rs.getString("p_city"));
                btn_name.setText(rs.getString("p_f_name"));
                btn_name2.setText(rs.getString("p_m_name"));
                btn_name3.setText(rs.getString("p_l_name"));
                btn_phone.setText(rs.getString("p_phoneNum"));
                String malee=rs.getString("p_gender");
                if(btn_male.equals(rs.getString("p_gender"))){
                      btn_male.setSelected(true);
                }else
                     btn_female.setSelected(true);
                  
                   
               btn_age.setSelectedItem(rs.getString("p_age"));
               btn_d1.setSelectedItem(rs.getString("p_dateDay"));
               btn_d2.setSelectedItem(rs.getString("p_dateMonth"));
               btn_d3.setSelectedItem(rs.getString("p_dateYear"));
               btn_bloodtype.setSelectedItem(rs.getString("p_bloodType"));
            }
 
            }
        } catch (SQLException ex) {
            Logger.getLogger(NurseForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_idKeyReleased

    /**
     * @param args the command line arguments
     */
    public static
            void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newpa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newpa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newpa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newpa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public
                    void run() {
                new newpa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Ubdate;
    private javax.swing.JTextField btn_add;
    private javax.swing.JComboBox<String> btn_age;
    private javax.swing.JComboBox<String> btn_bloodtype;
    private javax.swing.JTextField btn_city;
    private javax.swing.JComboBox<String> btn_d1;
    private javax.swing.JComboBox<String> btn_d2;
    private javax.swing.JComboBox<String> btn_d3;
    private javax.swing.JRadioButton btn_female;
    private javax.swing.JTextField btn_id;
    private javax.swing.JRadioButton btn_male;
    private javax.swing.JRadioButton btn_married;
    private javax.swing.JTextField btn_name;
    private javax.swing.JTextField btn_name2;
    private javax.swing.JTextField btn_name3;
    private javax.swing.JTextField btn_phone;
    private javax.swing.JButton btn_save;
    private javax.swing.JRadioButton btn_single;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
