/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package apps;

import java.sql.*;
import java.sql.DriverManager;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Mohammed Hussain
 */
public class SearchForDoc extends javax.swing.JFrame {

    Connection con;
    DefaultTableModel DTM;

    public SearchForDoc() {
        initComponents();
        setLocationRelativeTo(null);
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital", "root", "root");
        } catch (SQLException ex) {
            Logger.getLogger(SearchForDoc.class.getName()).log(Level.SEVERE, null, ex);
        }
        ShowDataInTable();
    }

    public void ShowDataInTable() {
        try {
            PreparedStatement stmt = con.prepareStatement("select *from doctor");
            ResultSet rs = stmt.executeQuery();
            while (rs.next()) {

                int id = rs.getInt("doctor_id");
                String password = rs.getString("d_password");
                String username = rs.getString("d_username");
                String name = rs.getString("d_name");
                int phone = rs.getInt("d_phoneNum");
                String address = rs.getString("d_address");
                String spe = rs.getString("d_sep");
                String dept = rs.getString("d_dept");
                String gender = rs.getString("d_gender");
                int age = rs.getInt("d_age");
                String join = rs.getString("d_join");
                String leave = rs.getString("d_leave");
                Object[] obj = {id, password, username, name, phone, address, spe, dept, gender, age, join, leave};
                DTM = (DefaultTableModel) doctor_table.getModel();
                DTM.addRow(obj);

            }

        } catch (SQLException ex) {
            Logger.getLogger(SearchForDoc.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void search(String str) {
        DTM = (DefaultTableModel) doctor_table.getModel();
        TableRowSorter<DefaultTableModel> def = new TableRowSorter<>(DTM);
        doctor_table.setRowSorter(def);
        def.setRowFilter(RowFilter.regexFilter(str));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_textsearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        doctor_table = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("search for doctor");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_textsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btn_textsearchKeyReleased(evt);
            }
        });
        jPanel1.add(btn_textsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 390, 65));

        doctor_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Password", "Username", "Name", "Phone ", "Address", "Specialization", "Department", "Gender", "Age", "Join Time", "Leave Time"
            }
        ));
        jScrollPane1.setViewportView(doctor_table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 780, 376));

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 500, -1, -1));

        jButton1.setText("delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 500, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Search");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, 140, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wallpapersy.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        choosesearch af = new choosesearch();
        af.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn_textsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_textsearchKeyReleased
        String searchfor = btn_textsearch.getText();
        search(searchfor);
    }//GEN-LAST:event_btn_textsearchKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {

            if (doctor_table.getSelectedRowCount() == 1) {
                PreparedStatement stmt = con.prepareStatement("delete from doctor where doctor_id=?");
                stmt.setInt(1, (int) doctor_table.getValueAt(doctor_table.getSelectedRow(), 0));
                stmt.executeUpdate();
//            dtm.removeRow(jTable1.getSelectedRow());

                DTM.removeRow(doctor_table.getSelectedRow());
                JOptionPane.showMessageDialog(this, "The Deletion Is Succeful");
            } else {
                if (doctor_table.getSelectedRowCount() == 0) {
                    JOptionPane.showMessageDialog(this, "Please Select A Row For Delete");
                } else {
                    JOptionPane.showMessageDialog(this, "Pleas Select Only One Row ");
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(SearchForDoc.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchForDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchForDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchForDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchForDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchForDoc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField btn_textsearch;
    private javax.swing.JTable doctor_table;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
